#!/usr/bin/env python3
"""Generate the theme from the shared snippet; never edit theme.css by hand."""
import argparse
import colorsys
import json
from pathlib import Path

root = Path(__file__).resolve().parents[1]
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--check', action='store_true', help='Check without writing files')
args = parser.parse_args()
manifest = json.loads((root / 'manifest.json').read_text())
version = (root / 'VERSION').read_text().strip()
assert manifest['version'] == version, 'VERSION and theme manifest differ'
assert json.loads((root / 'versions.json').read_text())[version] == manifest['minAppVersion']
assert json.loads((root / 'package.json').read_text())['version'] == version
snippet = (root / 'snippets/bear.css').read_text()
# Theme-only UI accent. An explicit accent chosen in Appearance still wins.
h, lightness, saturation = colorsys.rgb_to_hls(221 / 255, 76 / 255, 79 / 255)
header = f'''/* Bear Style {version} — generated by scripts/build_theme.py.
   Shared note styling lives in snippets/bear.css. No fonts are bundled. */
body {{
  --accent-h: {h * 360:.4f};
  --accent-s: {saturation * 100:.4f}%;
  --accent-l: {lightness * 100:.4f}%;
}}

'''
# The snippet's installation header does not apply to a standalone theme.
output = header + snippet.split('*/', 1)[1].lstrip()
target = root / 'theme.css'
if args.check:
    if not target.exists() or target.read_text() != output:
        raise SystemExit('theme.css is stale; run npm run build')
    print('Theme, shared snippet, and version metadata agree.')
else:
    target.write_text(output)
    print(target)
